Repository bc-back-end-study/board-kata, pull requests merged in 2023-03, with the labels that each got.

#2 db 설정
  build.gradle
  src/main/kotlin/com/kata/board/config/JasyptConfig.kt
  src/main/resources/application.properties
Labels: 💡 기능개발

#4 database setting
  build.gradle
  src/main/resources/application.properties
Labels: 💡 기능개발

#6 db 추가 설정 & 엔티티 설정
  build.gradle
  src/main/kotlin/com/kata/board/config/DataSourceConfig.kt
  src/main/kotlin/com/kata/board/config/JpaConfiguration.kt
  src/main/kotlin/com/kata/board/entity/BaseEntity.kt
  src/main/kotlin/com/kata/board/entity/Comment.kt
  src/main/kotlin/com/kata/board/entity/Post.kt
  src/main/kotlin/com/kata/board/entity/User.kt
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ♻️ 리팩토링, 💡 기능개발

#5 엔티티 설정
  build.gradle
  src/main/java/com/kata/board/config/JpaConfiguration.kt
  src/main/java/com/kata/board/entity/BaseEntity.java
  src/main/java/com/kata/board/entity/Comment.java
  src/main/java/com/kata/board/entity/Post.java
  src/main/java/com/kata/board/entity/User.java
Labels: 💡 기능개발

#7 Entity 생성
  build.gradle
  src/main/java/com/kata/board/controller/HelloController.java
  src/main/java/com/kata/board/entity/Comment.java
  src/main/java/com/kata/board/entity/Post.java
  src/main/java/com/kata/board/entity/User.java
Labels: 💡 기능개발

#8 엔티티 설정
  build.gradle
  src/main/java/com/kata/borad/entity/Comment.java
  src/main/java/com/kata/borad/entity/Post.java
  src/main/java/com/kata/borad/entity/User.java
Labels: ♻️ 리팩토링, 💡 기능개발

#9 java -> kotlin 마이그레이션
  build.gradle
  src/main/java/com/kata/board/BoardKataApplication.kt
  src/main/java/com/kata/board/config/DataSourceConfig.kt
  src/main/java/com/kata/board/config/JasyptConfig.kt
  src/main/java/com/kata/board/controller/HelloController.java
  src/main/java/com/kata/board/controller/HelloController.kt
  src/main/java/com/kata/board/entity/BaseEntity.java
  src/main/java/com/kata/board/entity/BaseEntity.kt
  src/main/java/com/kata/board/entity/Comment.java
  src/main/java/com/kata/board/entity/Comment.kt
  src/main/java/com/kata/board/entity/Post.java
  src/main/java/com/kata/board/entity/Post.kt
  src/main/java/com/kata/board/entity/User.java
  src/main/java/com/kata/board/entity/User.kt
Labels: ♻️ 리팩토링

#14 게시판 조회 기능
  src/main/java/com/kata/board/service/PostService.java
  src/main/java/com/kata/borad/entity/Post.java
  src/main/java/com/kata/borad/repository/PostRepository.java
Labels: 💡 기능개발

#13 조회 기능 구현 (Repository)
  build.gradle
  src/main/java/com/kata/board/repository/BoardRepository.kt
  src/main/java/com/kata/board/repository/PostRepository.kt
  src/main/java/com/kata/board/repository/PostRepositoryImpl.kt
  src/main/kotlin/com/kata/board/entity/BaseEntity.kt
  src/main/kotlin/com/kata/board/entity/Post.kt
Labels: ♻️ 리팩토링, 💡 기능개발

#16 조회 기능 구현 (Service)
  src/main/java/com/kata/board/repository/BoardJpaRepository.kt
  src/main/java/com/kata/board/repository/post/PostRepository.kt
  src/main/java/com/kata/board/repository/post/PostRepositoryImpl.kt
  src/main/java/com/kata/board/service/PostService.kt
  src/main/java/com/kata/board/service/PostServiceImpl.kt
  src/main/kotlin/com/kata/board/dto/PostDto.kt
  src/main/kotlin/com/kata/board/entity/BaseEntity.kt
  src/main/kotlin/com/kata/board/entity/Post.kt
  src/main/kotlin/com/kata/board/entity/User.kt
Labels: ♻️ 리팩토링, 💡 기능개발

#17 게시판 service layer 구현
  src/main/java/com/kata/board/entity/User.kt
  src/main/java/com/kata/board/post/domain/Post.kt
  src/main/java/com/kata/board/post/service/PostService.kt
  src/main/java/com/kata/board/post/service/response/PagingResponse.kt
  src/test/java/com/kata/board/post/service/PostServiceTest.kt
  src/test/resources/application.yaml
Labels: 💡 기능개발
